// Generated by AvoCode VERSION 0.0.1, PLEASE EDIT WITH CARE
/* eslint-disable */


var amplitude = require("avo-amplitude-js");

var amplitudeDevApiKey = "26aeb7d9e9737f62d9bc9d10f7efdc9a";
var amplitudeProdApiKey = "26aeb7d9e9737f62d9bc9d10f7efdc9a";

if (process.env.NODE_ENV !== "production") {
  amplitude.init(amplitudeDevApiKey);
} else {
  amplitude.init(amplitudeProdApiKey);
}

var asserts;

if (process.env.NODE_ENV !== "production") {
  asserts = require("avo-assert-js");
}

var requestCutestuff = function(numberOfCutestuffsInSession) {
  if (process.env.NODE_ENV === "development") {
    assertNumberOfCutestuffsInSession(numberOfCutestuffsInSession);
  }
  
  if (process.env.NODE_ENV === "development") {
    console.log("[avo] Event sent:", "Request Cutestuff", {
      "Number of Cutestuffs in Session": numberOfCutestuffsInSession});
  }
  
  amplitude.logEvent("Request Cutestuff", {
    "Number of Cutestuffs in Session": numberOfCutestuffsInSession});
};

var copyShareLink = function(link) {
  if (process.env.NODE_ENV === "development") {
    assertLink(link);
  }
  
  if (process.env.NODE_ENV === "development") {
    console.log("[avo] Event sent:", "Copy Share Link", {"Link": link});
  }
  
  amplitude.logEvent("Copy Share Link", {"Link": link});
};

if (process.env.NODE_ENV === "development") {
  var assertNumberOfCutestuffsInSession = function(numberOfCutestuffsInSession) {
    asserts.assertInt("Number of Cutestuffs in Session", 
      numberOfCutestuffsInSession);
    asserts.assertMin("Number of Cutestuffs in Session", 1, 
      numberOfCutestuffsInSession);
  };
  
  var assertLink = function(link) {
    asserts.assertString("Link", link);
  };
}

exports.requestCutestuff = requestCutestuff;
exports.copyShareLink = copyShareLink;

